### ISSUE TITLE
measurement.WindowOverview.ListView.Entry is null

### ISSUE THREAD

**Issue by asdfasdf100500** [Arcitectus/Sanderling#11] opened 2017-03-14 13:51 UTC
WindowOverview.ListView.Entry is null

Seems to affect other ListViews too

Probably due to recent EVE update

**Comment by Viir** [comment] 2017-03-14 23:05
I will add guidance about how to go about such an issue soon.
It will probably start with how to reproduce the issue in Visual Studio using a process sample from the eve online client.

Anyone who wants to work on this will need such a sample. See the guide at http://forum.botengine.de/t/collecting-samples-for-memory-reading-development/50 for how to collect such a sample.

**Comment by asdfasdf100500** [comment] 2017-03-15 08:04
I'm more than willling to try and fix this according to your guide.

I work as a software engineer, but I have very little experience with Python memory management and memory reading in general.

**Comment by Statter** [comment] 2017-03-15 10:34
I can confirm, that the Entry object is "null ". It has become that right after the latest update.
WindowInventory.[AnyViewType].Entry is null
WindowOverview.[AnyViewType].Entry is null
I think, that all windows are affected.
They are null both in Parsed and not Parsed memory measurments.

**Comment by Viir** [comment] 2017-03-15 22:05
@asdfasdf100500 Thanks for offering to help with this. Usually, adjustments to python reading code are not needed. Most of the time when something broke, CCP simply changed some symbols for types or type members in their code.

I added the memory reading code to the repository as well as guidance on how to reproduce the memory reading and inspect its results. See the guide at https://github.com/Arcitectus/Sanderling/blob/master/guide/Adapt-memory-reading.md

**Comment by Viir** [comment] 2017-03-16 20:18
> WindowOverview.ListView.Entry is null
> Seems to affect other ListViews too

@asdfasdf100500, what about `WindowOverview.ListView`? Is this null too?
The only assignment to the `Entry` property I see is in [`SictAuswertGbsListViewport<EntryT>.Berecne`](https://github.com/Arcitectus/Sanderling/blob/master/src/Sanderling/Sanderling.MemoryReading/Production/MemoryMeasurement/SictGbs/AuswertGbs.List.Viewport.cs#L571). If the `ListView` itself is found, we should take a closer look at that method and the intermediate results there.
Is there the `Scroll` in there found?

**Comment by Statter** [comment] 2017-03-16 20:26
![image 2](https://cloud.githubusercontent.com/assets/26432436/24017145/e7bacdc0-0a9f-11e7-9d16-ef9dc10e0642.png)

**Comment by Viir** [comment] 2017-03-16 20:54
Ok, so in the screenshot of the API explorer @Statter posted I see that the `Scroll` property the instance of `ListViewAndControl<EntryT>` is not null.
Now there is not much more left in between computation of `Scroll` and `Entry`:
+ Do we have instances for `ScrollClipperContentAst`?
+ AFAIR, the number of items in `ScrollClipperContentAst?.ListeChild` should equal the number of entries in the list. What do we have here?

**Comment by dreambottle** [comment] 2017-03-17 23:58
The ScrollClipperContentAst itself is not null, but the ScrollClipperContentAst.ListeChild returns null for the Overview window

**Comment by dreambottle** [comment] 2017-03-18 00:59
Ok, I think I found the root cause. Please review #12.

P.S. Sanderling works notably faster with the sensor branch, where you removed linking to the memreading dll.

**Comment by Viir** [comment] 2017-03-18 11:47
>P.S. Sanderling works notably faster with the sensor branch, where you removed linking to the memreading dll.
Thank you for reviewing the functionality of this change. I merged this into master together with your fix.

**Comment by Viir** [comment] 2017-03-18 12:05
A summary of what I see in the commit ad1c44f647a733bb4e67d0425be90c48f5444ee1 contributed by dreambottle:

### First some context
The memory reading expects the ListViews items to be contained in a `Scroll`. The scroll UIElement contains the actual item in one of its child nodes. The scroll can also contain other stuff like a scroll handle the user can interact with. So when reading the `Scroll`, we want to find different things in there and the items are to be found in the portion labeled as `Content` in the code.

### Dreambottle changed how the `Content` node is selected
The `SuuceFlacMengeAstFrüheste` method used for this selection step first does a Breadth-first search within the node passed as the first argument and returns the first node which matches the predicate which is passed as the second argument. The changed line only affects the predicate and makes it more restrictive.
So the reason for the old version failing could be the introduction of another node in the UITree which matches the predicate and comes first in the breadth-first order but is not the node which contains the nodes for the items in the list view.

**Comment by Viir** [comment] 2017-03-19 17:21
I created release v17.02.17 containing the fix from dreambottle.
@asdfasdf100500 does that release resolve the issue?

**Comment by asdfasdf100500** [comment] 2017-03-19 17:27
Yup, works perfectly.

**Closed** 2017-03-20 05:30 UTC
